### ISSUE TITLE
mantain status

### ISSUE THREAD

**Issue by lazymonkey2** [Soushi-Atsumi/Open-in-Sidebar#12]
Hello,
is it possibile to mantain status when changing the sidebar?
I explain:
I use bookmarkos.com to store my bookmarks, and I want to show them in the firefox sidebar using your extension.
In my bookmarks I have many folders and subfolders, that I can navigate in the sidebar.
But when I momentariliy change the sidebar (like from Open in sidebar to History) and then go back to Open in sidebar the page is reloaded and I loose the folder I had opened before.
Is is possibile to remember the status of the sidebar?
Thanks.

**Comment by Soushi-Atsumi** [comment]
Hi, lazymonkey2

It is impossible. When the sidebar switches to different one, it requires reloading. This is behavior of Firefox.
Basically the feature like remembering the status should be implemented by a service provider (in this case it is Bookmark OS). I don't know that they provide you this service via a website or Firefox extension but they should be able to materialize the feature.

**Comment by lazymonkey2** [comment]
ok thank you anyway for looking into it.
