### ISSUE TITLE
CSS style conflict?

### ISSUE THREAD

**Issue by logusergithub** [Soushi-Atsumi/Open-in-Sidebar#18]
Hi again,

1) it does not affect the opening of options, tutorial or anything else
2) it only happens with the toggle action via the icon on toolbar without anything being done yet

Just for reporting and maybe it doesn't even depend on the extension. If in userChrome.css I try to hide .sidebar-splitter after removing #sidebar-header, when I try to open with the extension icon the sidebar (after starting Firefox) it closes right away.

```
.sidebar-splitter {
opacity: 0 !important;
}
```

**Comment by Soushi-Atsumi** [comment]
Hi, logusergithub

Thanks for reporting, as you said, this is not problem of this extension.
