### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by u-Sir** [Soushi-Atsumi/Open-in-Sidebar#3]
- auto hide sidebar if not trigger 'open in sidebar' or add a hotkey to show/hide the sidebar
- previous/forward in sidebar
- select text in sidebar
- drag&drop url to open in sidebar,  similar to 'Prevue Popup'
![图片](https://user-images.githubusercontent.com/93647031/222914391-569a900e-5b35-4b9b-b1b9-6a16278ef005.png)

**Comment by u-Sir** [comment]
> Hi, u-Sir.
> 
> > * auto hide sidebar if not trigger 'open in sidebar' or add a hotkey to show/hide the sidebar
> 
> I think hiding a sidebar is annoying for a user when a user does not trigger 'open in sidebar'. Adding a hotkey for opening or closing a sidebar surely improve usability. I will implement it.
> 
> > ```
> > * previous/forward in sidebar
> > ```
> 
> Currently Firefox does not support this. Injecting a script to a page in a sidebar makes this possible but it may be hated.
> 
> > ```
> > * select text in sidebar
> > ```
> 
> Currently Firefox does not support this. By the way, you can select text in textbox (e.g. search box) in a sidebar.
> 
> > ```
> > * drag&drop url to open in sidebar,  similar to 'Prevue Popup'
> > ```
> 
> Currently Firefox does not support this. Perhaps injecting a script to a page in a sidebar makes this possible but it may be hated.
> 
> Some features cannot be added due to the restrictions. However, I improve this extension as possible as I can.

thanks. is there any way to make 'open in sidebar' more convenient?  I often use the right-click menu to 'open in sidebar', and the position sometimes changes .

**Comment by Soushi-Atsumi** [comment]
> thanks. is there any way to make 'open in sidebar' more convenient? I often use the right-click menu to 'open in sidebar', and the position sometimes changes .

If you use old version (2.2.1 or earlier), the position changes every time because of my bad coding.
> by the way, is it possible to have an option to 'open a link in the current tab(not in the sidebar)' when clicking a link in the sidebar?

Sadly Firefox does not provide a feature which an extension itself detects whether inside of sidebar or not. However, as an option, perhaps I can add "Always display 'open a link in the current tab'".

**Comment by Soushi-Atsumi** [comment]
I have released [v4.1.0](https://github.com/Soushi-Atsumi/Open-in-Sidebar/releases/tag/v4.1.0) which supports hotkey.
Closed by v4.1.0.
