### ISSUE TITLE
is it possible support open external links in sidebar?

### ISSUE THREAD

**Issue by u-Sir** [Soushi-Atsumi/Open-in-Sidebar#7]
i want the function like '[Open external links in a container](https://addons.mozilla.org/zh-CN/firefox/addon/open-url-in-container/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser)' do. so that I can integrated OiS into Fluent Search via cmd

**Comment by Soushi-Atsumi** [comment]
Hi, u-Sir

Unfortunately, Firefox does not allow to open a sidebar without [a user action](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/User_actions). So opening links via cmd is impossible currently.

**Comment by u-Sir** [comment]
OK
