### ISSUE TITLE
is it possible auto sets the zoom level in sidebar based on the screen resolution?

### ISSUE THREAD

**Issue by u-Sir** [Soushi-Atsumi/Open-in-Sidebar#8]
just like "[ffreszoom](https://addons.mozilla.org/zh-CN/firefox/addon/ffreszoom/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser)", change zoom level when the screen wider than specific value (px)
![图片](https://user-images.githubusercontent.com/93647031/227755724-45e531f9-73b0-40bf-8a64-5d24e162266b.png)
 this will improve the experience for dual monitor user which have different DPI
 
or add an option to switch between specific zoom level and default zoom level
![图片](https://user-images.githubusercontent.com/93647031/227763274-c708659b-2d05-489e-a939-f7f8b26896f0.png)

**Comment by Soushi-Atsumi** [comment]
Hi, u-Sir

This may be possible because ffreszoom can do. However, I don't need to add this feature because installing ffreszoom resolve this issue. If it doesn't resolve, it may be impossible for this add-on.

**Comment by u-Sir** [comment]
Unfortunately, ffreszoom doesn't work in sidebar 😂

**Comment by Soushi-Atsumi** [comment]
[It requires tabId to zoom](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/setZoom) but the sidebar does not have tabId. In conclusion, it is impossible to zoom for the sidebar with using API.
